In [124]:
import os
print(os.getcwd())

/home/linux_hy/anaconda3/envs/mc/Gas

In [125]:
cur_dir = os.getcwd() +'/Images2'
#videos = [str(x) for x in [2564, 2559, 2560, 2561, 2562, 2566, 2567, 2568, 2569, 2570, 2578, 2579, 2580, 2581, 2582]]
videos = [str(x) for x in [2564, 2559, 2560, 2566, 2567, 2568, 2578, 2579, 2580]]

num_frame = []
for video in videos:
    num_frame.append(len(os.listdir(cur_dir+'/'+video)))
    if len(os.listdir(cur_dir+'/'+video))==0:
        print(video)
print(num_frame)

[21783, 22624, 21845, 21815, 21830, 21460, 21860, 22617, 22094]

In [126]:
# videos = [str(x) for x in [2564, 2559, 2560, 2566, 2567, 2568, 2578, 2579, 2580]]

In [127]:
cur_dir = os.getcwd() +'/Images2'
#videos2 = [str(x) for x in [1242, 1237, 1238, 1239, 1240, 1467, 1468, 1469, 1470, 1471]]

videos2 = [str(x) for x in [1242, 1237, 1238, 1467, 1468, 1469]]
num_frame2 = []
for video in videos2:
    num_frame2.append(len(os.listdir(cur_dir+'/'+video)))
    if len(os.listdir(cur_dir+'/'+video))==0:
        print(video)
print(num_frame2)

[21860, 22875, 22115, 22079, 22132, 22190]

In [128]:
"""
import cv2

numbers = [2564, 2559, 2560, 2561, 2562, 2563, 1242, 1237, 1238, 1239, 1240, 1241, 2566, 2567, 2568, 2569, 2570, 2571, 2578, 2579, 2580, 2581, 2582, 2583, 1467, 1468, 1469, 1470, 1471, 1472, 1473]
for n in numbers:
    dir_path = os.getcwd()
    #print(dir_path)
    video_name = dir_path + '/Videos/MOV_' + str(n) + '.mp4'
    vidcap = cv2.VideoCapture(video_name)
    success, image = vidcap.read()
    count = 0
    new_path = dir_path + '/Images/'+str(n)
    while success:
        cv2.imwrite(new_path+"/%04d.jpg" % count, image)     # save frame as JPEG file
        success,image = vidcap.read()
        #print('Read a new frame: ', success)
        count += 1
"""

'\nimport cv2\n\nnumbers = [2564, 2559, 2560, 2561, 2562, 2563, 1242, 1237, 1238, 1239, 1240, 1241, 2566, 2567, 2568, 2569, 2570, 2571, 2578, 2579, 2580, 2581, 2582, 2583, 1467, 1468, 1469, 1470, 1471, 1472, 1473]\nfor n in numbers:\n    dir_path = os.getcwd()\n    #print(dir_path)\n    video_name = dir_path + \'/Videos/MOV_\' + str(n) + \'.mp4\'\n    vidcap = cv2.VideoCapture(video_name)\n    success, image = vidcap.read()\n    count = 0\n    new_path = dir_path + \'/Images/\'+str(n)\n    while success:\n        cv2.imwrite(new_path+"/%04d.jpg" % count, image)     # save frame as JPEG file\n        success,image = vidcap.read()\n        #print(\'Read a new frame: \', success)\n        count += 1\n'

In [129]:
import pandas as pd

# Specify the path to your CSV file
csv_file_path = os.getcwd() + "/GasVid Logging File.csv"

# Read the CSV file into a DataFrame
try:
    df = pd.read_csv(csv_file_path)

    # Display the first few rows of the DataFrame
    print(df.columns)

except FileNotFoundError:
    print(f"File not found: {csv_file_path}")
except pd.errors.EmptyDataError:
    print(f"The CSV file at {csv_file_path} is empty or contains no data.")
except pd.errors.ParserError:
    print(f"Error parsing the CSV file at {csv_file_path}. Check if it's a valid CSV file.")
except Exception as e:
    print(f"An error occurred: {str(e)}")

Index(['Video No.', 'Imaging Distance to the leak (m)', 'Date',
       'Shooting Time', 'Start Time for Leak 0 Video Clip',
       'Start Time for Leak 1 Video Clip'],
      dtype='object')

In [130]:
df = df[:31]
df.loc['Start Time for Leak 0 Video Clip':'Start Time for Leak 1 Video CLip'].astype(int)
df

,Video No.,Imaging Distance to the leak (m),Date,Shooting Time,Start Time for Leak 0 Video Clip,Start Time for Leak 1 Video Clip
0,2564,4.6,7/13/17,11:28,16,196
1,2559,6.9,7/13/17,9:10,29,209
2,2560,9.8,7/13/17,9:37,17,197
3,2561,12.6,7/13/17,10:04,19,199
4,2562,15.6,7/13/17,10:43,24,204
5,2563,18.6,7/13/17,11:00,11,191
6,1242,4.6,7/13/17,11:30,5,185
7,1237,6.9,7/13/17,9:14,19,199
8,1238,9.8,7/13/17,9:44,4,184
9,1239,12.6,7/13/17,10:10,5,185
10,1240,15.6,7/13/17,10:34,7,187
11,1241,18.6,7/13/17,11:03,6,186
12,2566,4.6,7/13/17,12:25,19,199
13,2567,6.9,7/13/17,12:38,7,187
14,2568,9.8,7/13/17,13:04,0,157
15,2569,12.6,7/13/17,13:30,17,197
16,2570,15.6,7/13/17,13:55,30,210
17,2571,18.6,7/13/17,14:19,27,207
18,2578,4.6,7/14/17,8:22,26,206
19,2579,6.9,7/14/17,8:53,17,197
20,2580,9.8,7/14/17,9:21,27,207
21,2581,12.6,7/14/17,9:48,29,209
22,2582,15.6,7/14/17,10:17,11,371
23,2583,18.6,7/14/17,11:04,34,214
24,1467,4.6,7/14/17,8:25,18,198
25,1468,6.9,7/14/17,8:59,5,185
26,1469,9.8,7/14/17,9:26,9,189
27,1470,12.6,7/14/17,9:56,3,183
28,1471,15.6,7/14/17,10:22,166,346
29,1472,18.6,7/14/17,11:03,4,184
30,1473,8.8,7/14/17,11:37,1,181

In [131]:
import datetime as dt
import time
import numpy as np
#df.loc['Start Time for Leak 0 Video Clip':'Start Time for Leak 1 Video Clip'] = df.loc['Start Time for Leak 0 Video Clip':'Start Time for Leak 1 Video Clip'].astype('str')
#print(df.dtypes)
df['Video No.'] = df['Video No.'].astype(str)
df.set_index('Video No.', drop=False, inplace=True)
print(df.index)
print(df.columns)

Index(['2564', '2559', '2560', '2561', '2562', '2563', '1242', '1237', '1238',
       '1239', '1240', '1241', '2566', '2567', '2568', '2569', '2570', '2571',
       '2578', '2579', '2580', '2581', '2582', '2583', '1467', '1468', '1469',
       '1470', '1471', '1472', '1473'],
      dtype='object', name='Video No.')
Index(['Video No.', 'Imaging Distance to the leak (m)', 'Date',
       'Shooting Time', 'Start Time for Leak 0 Video Clip',
       'Start Time for Leak 1 Video Clip'],
      dtype='object')

In [132]:
import natsort
import shutil

cur_dir = os.getcwd()
#videos = os.listdir(cur_dir)
total = sum(num_frame)
labels = []
label_train = []
label_test = []
image_names = []
image_name_train = []
image_name_test = []
#train = [str(x) for x in [2564, 2559, 2560, 2561, 2562, 2566, 2567, 2568, 2569, 2570, 2578, 2579, 2580, 2581, 2582]]
train = [str(x) for x in [2564, 2559, 2560, 2566, 2567, 2568, 2578, 2579, 2580]]

for idx, video in enumerate(train):
    #src = cur_dir + '/Images/%d/'%video
    print(video)
    starttime0 = df.at[video, 'Start Time for Leak 0 Video Clip']
    starttime1 = df.at[video, 'Start Time for Leak 1 Video Clip']
    #starttime = [starttime0, starttime1+180, starttime1+900, starttime1+1260]
    starttime = [starttime0*15+1, (starttime1+180)*15+2, (starttime1+900)*15+2, num_frame[idx]]
    print(starttime)
    lines = []
    for label in range(len(starttime)-1):
        s = starttime[label]
        e = starttime[label+1]
        for idx in range(s, e-4):
            lines.append("{} {} {} {}\n".format('%s'%video, idx, idx+5, label))
    with open('train.txt', 'a') as f:
        f.writelines(lines)
    #image_files = natsort.natsorted(os.listdir(dir))
    #label = -1
    """
    with open('train.txt', 'a') as f:
        annotation_string1 = "{} {} {} {}\n".format('%s'%video, starttime[0]*15+1, starttime[1]*15+1, 0)
        annotation_string2 = "{} {} {} {}\n".format('%s'%video, starttime[1]*15+2, starttime[2]*15+1, 1)
        annotation_string3 = "{} {} {} {}\n".format('%s'%video, starttime[2]*15+2, num_frame[idx], 2)
        f.writelines([annotation_string1, annotation_string2, annotation_string3])
    """
f.close()
"""
    for image_name in image_files:
        frame_number = int(image_name.split('_')[1].split('.')[0])
        if starttime[0]*15 <= frame_number <= starttime[1] *15:
            label = 0
        elif starttime[1]* 15 + 1 <= frame_number <= starttime[2] * 15:
            label = 1
        elif starttime[2] * 15 + 1 <= frame_number <= starttime[3] * 15 :
            label = 2
        if 0 <= label <= 2:
            shutil.move(src+'/img_%05d.jpg'%frame_number, dir + '/img_%05d.jpg'%frame_number)
            image_names.append(dir + image_name)
            image_name_train.append(dir+image_name)
            labels.append(label)
            label_train.append(label)
df_train = pd.DataFrame({'Image_Name': image_name_train, 'Label':label_train})
"""
# test = [str(x) for x in [1242, 1237, 1238, 1239, 1240, 1467, 1468, 1469, 1470, 1471]]
test = [str(x) for x in [1242, 1237, 1238, 1467, 1468, 1469]]

for idx, video in enumerate(test):
    print(video)
    starttime0 = df.at[video, 'Start Time for Leak 0 Video Clip']
    starttime1 = df.at[video, 'Start Time for Leak 1 Video Clip']
    starttime = [starttime0*15+1, (starttime1+180)*15+2, (starttime1+900)*15+2, num_frame2[idx]]
    print(starttime)
    lines = []
    for label in range(len(starttime)-1):
        s = starttime[label]
        e = starttime[label+1]
        for idx in range(s, e-4):
            lines.append("{} {} {} {}\n".format('%s'%video, idx, idx+5, label))
    with open('test.txt', 'a') as f:
        f.writelines(lines)
    """
    with open('test.txt', 'a') as f:
        annotation_string1 = "{} {} {} {}\n".format('%s'%video, starttime[0]*15, starttime[1]*15, 0)
        annotation_string2 = "{} {} {} {}\n".format('%s'%video, starttime[1]*15+1, starttime[2]*15, 1)
        annotation_string3 = "{} {} {} {}\n".format('%s'%video, starttime[2]*15+1, starttime[3]*15, 2)
        f.writelines([annotation_string1, annotation_string2, annotation_string3])
    """
f.close()
"""
    image_files = natsort.natsorted(os.listdir(dir))
    
    abel = -1

    for image_name in image_files:
        frame_number = int(image_name.split('_')[1].split('.')[0])
        if starttime[0]*15 <= frame_number <= starttime[1] *15:
            label = 0
        elif starttime[1]* 15 + 1 <= frame_number <= starttime[2] * 15:
            label = 1
        elif starttime[2] * 15 + 1 <= frame_number <= starttime[3] * 15 :
            label = 2
        if 0 <= label <= 2:
            image_names.append(dir + image_name)
            image_name_test.append(dir+image_name)
            labels.append(label)
            label_test.append(label)         

df_test = pd.DataFrame({'Image_Name': image_name_test, 'Label' : label_test})

df1 = pd.DataFrame({'Image_Name': image_names, 'Label':labels})
#csv_file_path = cur_dir + '/' + 'label.csv'
#df1.to_csv(csv_file_path, index=False, header=False)
"""

2564
[241, 5642, 16442, 21783]
2559
[436, 5837, 16637, 22624]
2560
[256, 5657, 16457, 21845]
2566
[286, 5687, 16487, 21815]
2567
[106, 5507, 16307, 21830]
2568
[1, 5057, 15857, 21460]
2578
[391, 5792, 16592, 21860]
2579
[256, 5657, 16457, 22617]
2580
[406, 5807, 16607, 22094]
1242
[76, 5477, 16277, 21860]
1237
[286, 5687, 16487, 22875]
1238
[61, 5462, 16262, 22115]
1467
[271, 5672, 16472, 22079]
1468
[76, 5477, 16277, 22132]
1469
[136, 5537, 16337, 22190]

"\n    image_files = natsort.natsorted(os.listdir(dir))\n    \n    abel = -1\n\n    for image_name in image_files:\n        frame_number = int(image_name.split('_')[1].split('.')[0])\n        if starttime[0]*15 <= frame_number <= starttime[1] *15:\n            label = 0\n        elif starttime[1]* 15 + 1 <= frame_number <= starttime[2] * 15:\n            label = 1\n        elif starttime[2] * 15 + 1 <= frame_number <= starttime[3] * 15 :\n            label = 2\n        if 0 <= label <= 2:\n            image_names.append(dir + image_name)\n            image_name_test.append(dir+image_name)\n            labels.append(label)\n            label_test.append(label)         \n\ndf_test = pd.DataFrame({'Image_Name': image_name_test, 'Label' : label_test})\n\ndf1 = pd.DataFrame({'Image_Name': image_names, 'Label':labels})\n#csv_file_path = cur_dir + '/' + 'label.csv'\n#df1.to_csv(csv_file_path, index=False, header=False)\n"

In [133]:
"""
import csv

csv_file_path2 = cur_dir+'/list.csv'
# with open(csv_file_path2,'w',newline='') as file:
#     writer = csv.writer(file)
#     writer.writerow()

df2 = pd.DataFrame(image_names)
df2.to_csv(csv_file_path2, header=False, index=False)
df_train.to_csv(cur_dir+'/train.csv', header=False, index=False)
df_test.to_csv(cur_dir+'/test/csv', header=False, index=False)
"""

"\nimport csv\n\ncsv_file_path2 = cur_dir+'/list.csv'\n# with open(csv_file_path2,'w',newline='') as file:\n#     writer = csv.writer(file)\n#     writer.writerow()\n\ndf2 = pd.DataFrame(image_names)\ndf2.to_csv(csv_file_path2, header=False, index=False)\ndf_train.to_csv(cur_dir+'/train.csv', header=False, index=False)\ndf_test.to_csv(cur_dir+'/test/csv', header=False, index=False)\n"

In [134]:
df2

NameError: name 'df2' is not defined